aussietravels-web/src/java/fit5042/ass1/controllers/SearchController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5042.ass1.controllers;

import fit5042.ass1.activity.ActivityDAO;
import fit5042.ass1.entities.Activity;
import fit5042.ass1.entities.Packages;
import fit5042.ass1.entities.Resorts;
import fit5042.ass1.entities.Users;
import fit5042.ass1.packages.PackagesDAO;
import fit5042.ass1.resort.ResortDAO;
import fit5042.ass1.util.ActivityResultList;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 *
 * @author Jishnu
 */
@Named(value = "searchController")
@SessionScoped
public class SearchController implements Serializable {

    
    @EJB
    private ResortDAO resortDAOImpl;
    
    @EJB
    private PackagesDAO packageDAOImpl;
    
    @EJB
    private ActivityDAO activityDAOImpl;
    

    private String PageTitle;
    private Map<String,String> resortsLocations;
    private Map<String,String> packageNames;
    private Map<String,String> activityNames;
    
    
    // For temp data storage
    private ArrayList<Packages> packages;
    private ArrayList<Resorts> resorts;
    private ArrayList<Activity> activity;
    
    private String resortLocationSelected;
    private String packageNameSelected;
    private String activityNameSelected;

   
    public SearchController() {
        
        PageTitle = "Search";
        resortsLocations = new HashMap<String, String>();
        packageNames = new HashMap<String, String>();
        activityNames  = new HashMap<String, String>();
        
        packages = new ArrayList<Packages>();
        resorts = new ArrayList<Resorts>();
        activity = new ArrayList<Activity>();
        
        
        
    }

   
    
    
    @PostConstruct
    public void init() {
    

        resorts = resortDAOImpl.getAllResorts();
        
        for(Resorts r : resorts)
        {
        
            resortsLocations.put(r.getResortName(), String.valueOf(r.getResortId()));
        
        
        }
        
        packages = packageDAOImpl.getAllPackages();
        
        for (Packages p : packages) {
        
            packageNames.put(p.getPackageName(), String.valueOf(p.getPackageId()));
        
        }
        
        
        activity = activityDAOImpl.getAllActivities();
        
        for (Activity a : activity) {
        
            activityNames.put(a.getActivityName(), String.valueOf(a.getActivityId()));
        
        }

        }
    
  
  /*
    * This method redirects user to the page to book resorts
    * @Param : 
    * @Return : 
    */
 public void  bookResorts()
 {
 
        
        String url = "https://localhost:11488/aussietravels-web/faces/public/bookResorts.xhtml?bookResorts=" + resortLocationSelected;
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(url);
        } catch (IOException ex) {
            Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
        }
 
 
 }   
 
 
 
 /*
    * This method redirects user to the page to book packages
    * @Param : 
    * @Return : 
    */
 public void bookPackages() {
 
 
      String url = "https://localhost:11488/aussietravels-web/faces/public/bookPackages.xhtml?package=" + packageNameSelected;
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(url);
        } catch (IOException ex) {
            Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
        }
 
 
 }
 
 
 /*
    * This method redirects user to the page to book activities
    * @Param : 
    * @Return : 
    */
  public void bookActivity() {
 
 
      String url = "https://localhost:11488/aussietravels-web/faces/public/bookActivities.xhtml?activity=" + activityNameSelected;
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(url);
        } catch (IOException ex) {
            Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
        }
 
 
 }
    
    
    
    
  // getters and setters
    
 public String getPageTitle() {
        return PageTitle;
    }

    public void setPageTitle(String PageTitle) {
        this.PageTitle = PageTitle;
    }

    public Map<String, String> getResortsLocations() {
        return resortsLocations;
    }

    public void setResortsLocations(Map<String, String> resortsLocations) {
        this.resortsLocations = resortsLocations;
    }

    public Map<String, String> getPackageNames() {
        return packageNames;
    }

    public void setPackageNames(Map<String, String> packageNames) {
        this.packageNames = packageNames;
    }


    public Map<String, String> getActivityNames() {
        return activityNames;
    }

    public void setActivityNames(Map<String, String> activityNames) {
        this.activityNames = activityNames;
    }

    public ArrayList<Packages> getPackages() {
        return packages;
    }

    public void setPackages(ArrayList<Packages> packages) {
        this.packages = packages;
    }

    public ArrayList<Resorts> getResorts() {
        return resorts;
    }

    public void setResorts(ArrayList<Resorts> resorts) {
        this.resorts = resorts;
    }

    public ArrayList<Activity> getActivity() {
        return activity;
    }

    public void setActivity(ArrayList<Activity> activity) {
        this.activity = activity;
    }

    public String getResortLocationSelected() {
        return resortLocationSelected;
    }

    public void setResortLocationSelected(String resortLocationSelected) {
        this.resortLocationSelected = resortLocationSelected;
    }

    public String getPackageNameSelected() {
        return packageNameSelected;
    }

    public void setPackageNameSelected(String packageNameSelected) {
        this.packageNameSelected = packageNameSelected;
    }

  

    public String getActivityNameSelected() {
        return activityNameSelected;
    }

    public void setActivityNameSelected(String activityNameSelected) {
        this.activityNameSelected = activityNameSelected;
    }
    
    
    
    
    
    
      }
    
    
    
    
    
   
    

aussietravels-web/web/compare.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
 <h:head>
     <h:outputStylesheet name="css/style.css"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css"/>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"></meta>
     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular-route.js"></script>
     <h:outputScript name="js/app.js"> </h:outputScript>
     <h:outputScript name="js/PokemonService.js"> </h:outputScript>
     <h:outputScript name="js/SearchController.js"></h:outputScript>
     <h:outputScript name="js/app.js"> </h:outputScript>
     <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
     <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css"/>
     <title> #{searchController.pageTitle}
 </title>
 </h:head>
<body class="body-background container" data-ng-app="ngCompare">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #060606">
        <h:link class="navbar-brand" outcome="index"> <h4>AUSSIE HOLIDAYS </h4></h:link>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
     </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ml-auto">
         <h:form>
        <li class="nav-item">
            <h:commandLink class="nav-link" action="#{navigation.showSearch()}">Home</h:commandLink>
        </li>
             </h:form>
        <li class="nav-item active">   
             <h:outputLink  class="nav-link" value="compare.xhtml"> Compare Packages </h:outputLink>
         </li>
         <li class="nav-item">
             <h:outputLink  class="nav-link" value="public/index.xhtml"> Login </h:outputLink>
        </li>
         <h:form>
         <li class="nav-item">
             <h:commandLink class="nav-link" action="#{navigation.register}" > Register </h:commandLink>
        </li>
        </h:form>
     </ul>
    </div>
  </nav>
    
    
   <div ng-view="true"></div>
    
    
</body>
    
    <style>
        
        th{
            
            color:black;
            
        }
        
        
    </style> 
    
    
  </html>

aussietravels-web/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
         <h:outputStylesheet name="css/style.css"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css"/>
     <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
     <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css"/>
        <title>ERROR</title>
    </h:head>
    <h:body class='error-body'>
        
        
        <div class="container" style="margin-top:120px">
            
            <div class="text-center">
            <h1 style='color: white'> OOPS</h1>
            <h1 style='color: white'> INVALID LOGIN ATTEMPT </h1> 
            <h:link outcome="login.xhtml" class="btn btn-lg btn-success">Take me back</h:link>
            </div>
        </div>
        

    </h:body>
</html>

aussietravels-web/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
 <h:head>
     <h:outputStylesheet name="css/style.css"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css"/>
     <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
     <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css"/>
     <title> #{searchController.pageTitle}</title>
 </h:head>
<h:body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #060606">
        <h:link class="navbar-brand" outcome="index"> <h4>AUSSIE HOLIDAYS </h4></h:link>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
     </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
            <h:link class="nav-link" outcome = "index">Home<span class="sr-only">(current)</span></h:link>
        </li>
        <li class="nav-item">   
             <h:outputLink  class="nav-link" value="compare.xhtml"> Compare Packages </h:outputLink>
         </li>
         <li class="nav-item">
             <h:outputLink  class="nav-link" value="public/index.xhtml"> Login </h:outputLink>
        </li>
         <h:form>
         <li class="nav-item">
             <h:commandLink class="nav-link" action="#{navigation.register}" > Register </h:commandLink>
        </li>
         </h:form>
     </ul>
    </div>
  </nav>
    
     <div id="slider">

        <div class="container search-box">
            <div class="text-center">
                        <h4 class="test-color"> I WOULD LIKE TO RESERVE A 
                            <select class="test-select" name="activity">
                                <option> __________ </option>
                                <option value="1"> RESORT </option>
                                <option value="2"> PACKAGES </option>
                                <option value="3"> ACTIVITY </option>
                    </select> </h4>
                <div style="margin-top:20px;">
                <h2 class="test-color resort-text" style="display: none"> STAY AND EXPLORE AUSTRALIA </h2>
                <h2 class="test-color package-text" style="display: none"> CONVERT TRIP TO JOURNEYS </h2>
                <h2 class="test-color activity-text" style="display: none"> UNRAVEL NEW EXPERIENCES </h2>
                </div>
            </div>
            
            
            <h:form  class="resort-form" style="display: none">
                <div class="row">
                    <div class="col-lg-9 offset-1 padding-0">
                        <!--
                        <input type="text" class="form-control form-control-lg search-input" placeholder="SELECT RESORT" />
                    -->
                    
                      <h:selectOneMenu class="form-control form-control-lg border-styled" 
                                       value="#{searchController.resortLocationSelected}">
                          <f:selectItems  value="#{searchController.resortsLocations}"/>
                        </h:selectOneMenu>

                    </div>  
                    
                    
                    <div class="col-lg-2 col-sm-2 padding-0">
                        
                        <h:commandButton class="btn-success btn btn-lg" value="BOOK"
                                     action="#{searchController.bookResorts()}"></h:commandButton>
                        
                    </div>
                    
                </div>
            </h:form>
            
            
            <!-- Display packages --> 
            
            <h:form class="package-form" style="display: none">
                <div class="row">
                    <div class="col-lg-9 offset-1 padding-0">
                        <!--
                        <input type="text" class="form-control form-control-lg search-input" placeholder="SELECT RESORT" />
                    -->
                     
                      <h:selectOneMenu class="form-control form-control-lg border-styled" 
                                       value="#{searchController.packageNameSelected}">
                          <f:selectItems  value="#{searchController.packageNames}"/>
                        </h:selectOneMenu>
                    
                        </div>
                 
                     <div class="col-lg-2 col-sm-2 padding-0">
                        
                        <h:commandButton class="btn-success btn btn-lg" value="BOOK"
                                     action="#{searchController.bookPackages()}"></h:commandButton>
                        
                    </div>
                    
                </div>
            </h:form>
            
            
              <!-- Display events --> 
              
              <h:form class="activity-form" style="display: none">
                <div class="row">
                    <div class="col-lg-9 offset-1 padding-0">
                        <!--
                        <input type="text" class="form-control form-control-lg search-input" placeholder="SELECT RESORT" />
                    -->
                    
                         <h:selectOneMenu class="form-control form-control-lg border-styled" 
                                          value="#{searchController.activityNameSelected}">
                             <f:selectItems  value="#{searchController.activityNames}"/>
                        </h:selectOneMenu>
                    
                    
                        </div>
                    
                    <div class="col-lg-2 col-sm-2 padding-0">
                   <h:commandButton class="btn-success btn btn-lg" value="BOOK"
                                    action="#{searchController.bookActivity()}"></h:commandButton>
                        
                    </div>
                </div>
            </h:form>
            
            
        </div>


        <div class="slide slide1">

            <div class="slide-content">

            </div>

        </div>

        <div class="slide slide2">

            <div class="slide-content">

            </div>

        </div>

        <div class="slide slide3">

            <div class="slide-content">

            </div>

        </div>



    </div>
    
    
    
    <footer>
        
        <div class="container">
            
            <div class="row">
            <div class="col-xs-12 col-md-6" >
                <h4 style="margin-top: 20px">AUSSIE HOLIDAYS </h4>
                <p style="margin-top: -10px"> 79 Whiteman Street </p>
                <p style="margin-top: -20px"> Melbourne, Australia </p>
                <p  style="margin-top: -20px"> Phone : 049999999 </p>
            </div>
            
            <div class=" col-md-2" style="margin-top: 60px;">
                
                <h6>About Us</h6>
        
            </div>
                
             <div class=" col-md-2" style="margin-top: 60px;">   
                <h6>Contact Us</h6>
             </div>
                
                
             <div class=" col-md-2" style="margin-top: 60px;">   
                <h6> <h:outputLink value="admin/index.xhtml"> Admin </h:outputLink></h6>
             </div>
                
                
                </div>
            
        </div>
        
    </footer>

    <h:outputScript name="js/carousel.js"> </h:outputScript>
 </h:body>
    
   
    
</html>

aussietravels-web/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"></meta>
     <h:outputStylesheet name="css/login.css"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css"/>
     <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
     <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css"/>
        <title>Login</title>
    </h:head>
    <h:body class="login-background">
        
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #060606">
        <h:link class="navbar-brand" outcome="index"> <h4>AUSSIE HOLIDAYS </h4></h:link>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
     </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ml-auto">
      <li class="nav-item">
            <h:link class="nav-link" outcome = "index">Home<span class="sr-only">(current)</span></h:link>
        </li>
         <li class="nav-item">
             <h:outputLink  class="nav-link active" value="public/index.xhtml"> Login </h:outputLink>
        </li>
         <h:form>
         <li class="nav-item">
             <h:commandLink class="nav-link" action="#{navigation.register}" > Register </h:commandLink>
        </li>
         </h:form>
     </ul>
    </div>
  </nav>
        
        
        
     <div class="login-page" style="margin-top: 60px;">
     <div class="form">
    <form class="register-form">
      <input type="text" placeholder="email"/>
      <input type="password" placeholder="password"/>
      <input type="text" placeholder="email address"/>
      <button>create</button>
      <p class="message">Already registered? <a href="#">Sign In</a></p>
    </form>
    <form class="login-form" method="POST" action="j_security_check">
        <h4 style="color:black"> Login </h4>
      <input type="text" required='true' placeholder="username" name="j_username"/>
      <input type="password" required='true' placeholder="password" name="j_password"/>
      <button type="submit">login</button>
    </form>
  </div>
</div>

        <h:outputScript name="js/login.js"></h:outputScript>
        
    </h:body>
</html>

aussietravels-web/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
     xmlns:f = "http://java.sun.com/jsf/core">
    <h:head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"></meta>
     <h:outputStylesheet name="css/login.css"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css"/>
     <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
     <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css"/>
        <title>User Registration</title>
    </h:head>
    <h:body class="login-background">
        
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #060606">
        <h:link class="navbar-brand" outcome="index"> <h4>AUSSIE HOLIDAYS </h4></h:link>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
     </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ml-auto">
      <li class="nav-item">
            <h:link class="nav-link" outcome = "index">Home<span class="sr-only">(current)</span></h:link>
        </li>
         <li class="nav-item">
             <h:outputLink  class="nav-link" value="public/index.xhtml"> Login </h:outputLink>
        </li>
         <h:form>
         <li class="nav-item">
             <h:commandLink class="nav-link active" action="#" > Register </h:commandLink>
        </li>
         </h:form>
     </ul>
    </div>
  </nav>
        
        
        
       <div class="login-page" style="margin-top: 60px;">
     <div class="form">
    <h:form class="login-form">
        <h3 style="color:black"> Sign Up </h3>
        
       <h:inputText class="form-control border-styled" id="email"  a:placeholder="Email"
                         required="true" requiredMessage="email is required"  value="#{signupController.email}" binding="#{email}"></h:inputText>
      <h:messages  for="email" class="#{!email.valid ? 'label label-warning' : 'none'}"/>
      <h:inputSecret class="form-control border-styled" id="password" a:placeholder="Password"
                     required="true" requiredMessage="password is required"  value="#{signupController.password}" binding="#{password}"></h:inputSecret>              
      <h:messages  for="password" class="#{!password.valid ? 'label label-warning' : 'none'}"/>
      
      <h:inputText id="firstName" class="form-control border-styled" a:placeholder="First Name" validatorMessage="The first name should start with capital letters and should have  should have two or more  alphabets "
                     label="Name" size="32" value="#{signupController.firstName}" binding="#{firstName}" required="true" requiredMessage="Please enter your first name!">
      <f:validateRegex pattern = "[A-Z][a-z]+" />
      </h:inputText> 
         
      <h:messages for="firstName" class="#{!firstName.valid ? 'label label-warning' : 'none'}" />
      
      
      
     <h:inputText id="lastName" class="form-control border-styled" a:placeholder="Last Name" validatorMessage="The last name should start with capital letters and should have two or more alphabets "
                     label="lastName" size="32" value="#{signupController.lastName}" binding="#{lastName}" required="true" requiredMessage="Please enter your last name!">
     <f:validateRegex pattern = "[A-Z][a-z]+" />
     </h:inputText> 
                              
     <h:messages for="lastName" class="#{!lastName.valid ? 'label label-warning' : 'none'}" />
      
      <h:inputText id="phone" class="form-control border-styled" a:placeholder="Phone Number" validatorMessage="Should be a valid mobile or land phone number "
                               label="phone" size="32" value="#{signupController.phoneNumber}" binding="#{phoneNumber}" required="true" requiredMessage="Please enter your phone Number!">
       <f:validateRegex pattern = "0[0-9]{9}|9[0-9]{7}" />
      </h:inputText> 
                              
      <h:messages for="phone" class="#{!phone.valid ? 'label label-warning' : 'none'}" />
              
        <h:inputText id="address" class="form-control border-styled address" a:placeholder="Address"
                        autocomplete="false"   label="adddress" size="32" value="#{signupController.address}" binding="#{address}" required="true" requiredMessage="Please enter your address!">
        </h:inputText> 
                    
      
       <h:messages for="address"  class="#{!address.valid ? 'label label-warning' : 'none'}" />
       
       <h:commandButton action="#{signupController.addNewUser()}" value="Sign Up" class="btn btn-success"
                         style="margin-top:30px; background-color: green">
            
        </h:commandButton>
        
            
       
      
                            
        
    </h:form>
  </div>
     </div>  
        
     <div class="login-page" style="margin-top: 60px;">
    
</div>

        <h:outputScript name="js/login.js"></h:outputScript>
        
    </h:body>
    
    
     <script>
 
    
   
    $(function(){
        $("#form").attr("autocomplete", "off");
    });

    
    
    $( function() {
    $( "#tabs" ).tabs();
     } );
  
       // Place search 
        function activatePlacesSearch() {

            var input = $(".address")[0];
            console.log(input);
            
            
            var autocomplete = new google.maps.places.Autocomplete(input);
            google.maps.event.addListener(autocomplete, 'place_changed', function () {
                var place = autocomplete.getPlace();
                console.log(place.address_components);
            });

        }

    </script>

    
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm-robUfxNpka3hxgsp2TbjwKpVM0Fufo&amp;libraries=places&amp;callback=activatePlacesSearch"> </script>
  
    
    
</html>